language: java
sudo: false
env:
  global:
    - # ^^ OSSRH_USER
    - secure: "iBhREAKe9rori2gk7UM8VkO9nVevniPRNrHRHNQh6+pofmp5Tswxf3lm6rIXmARJoJdyrQO3O2ZOYX3BOotmr85G+5CJQtPYy7BWyGMiP8dWbn5z0crNxdIjiyF9U4EFdfMiuO3Ys1rlpDjFkH0iYFwVwfDR3W0ySEWNP6zhU3A="
    - # ^^ OSSRH_PASSWORD
    - secure: "gVNhdL2ccZsy+fo1oEt18u7pwKjx55zA1QgGaELGZyo3VzjA1f1yHiCYHVYRMux/rIcKP1LvAHkMfGMiUP9fzpfvCDH0SRCEMTp7/1d9MR2uGBF590sqVB9S+GDwB5TGAVwFrqIxPE65Vl99Tv/WE95Ae0zONc8gtofJliMzPHA="
    - # ^^ GPG_KEY_NAME
    - secure: "BXOr+XYiAzs1n1/8XxltlCIXCZA/34bOkhX/EGwBH8LfTTw6RMfZEbtuDrCfPkSsaEA0NakAbCg0I9+mcagAbZKNEO1kPGIZRcBtEtz8oPICMYY1GJNcomCxU7+mBkXtqbgRVS7lkDXZJa3Aceqz/BP8/lgmp7UHVCyUHdroPOc="
    - # ^^ GPG_PASSPHRASE
    - secure: "NgdLziSLzCNvCFbs12YsEyXD+bjXEGc5SIp5ZDKxRdV97n7c70zP/17cVNSYrFMGSRlE4ZlMyxRLX2IZkVNk9KzDoaZyWsV4GH0pxy7cRn/Tfc4L9O6YEHMQNHt/LCsY0eXSMZNZ1BS17L1ltfflwi+dgTpE2J+jEpZbNsQ+bkU="

before_install:
  - 'if [[ ${TRAVIS_TAG} != "" ]]; then mvn versions:set -DnewVersion="${TRAVIS_TAG}"; fi'

script: mvn clean verify

after_success:
  - openssl aes-256-cbc -K $encrypted_b6c74d7f8e86_key -iv $encrypted_b6c74d7f8e86_iv -in codesigning.asc.enc -out codesigning.asc -d
  - gpg --fast-import codesigning.asc --yes
  - mvn jacoco:report coveralls:report
  - "[[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} == '' ]] && mvn deploy -DreposityId=sonatype-nexus-snapshots -Psign-artifacts -DskipTests --settings deploy-settings.xml"
  - "[[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} != '' ]] && mvn deploy -DreposityId=sonatype-nexus-staging -Psign-artifacts -DskipTests --settings deploy-settings.xml"
